<?php

namespace App\Forms\EAV;

use App\Forms\FormMessage;
use App\Forms\FormRedirect;
use App\Model\Database\EAV\EAVRepository;
use Nette\Application\AbortException;
use Nette\Application\UI\Form;
use Nette\Application\UI\InvalidLinkException;
use Nette\Application\UI\Presenter;

class EditSpecificEntityForm extends SpecificEntityForm
{
    private array $entityData;

    public function __construct(protected Presenter $presenter, protected EAVRepository $EAVRepository, private string $rowUnique)
    {
        parent::__construct($this->presenter, $this->EAVRepository);

        $this->entityData = $this->EAVRepository->findByUnique($this->rowUnique);
    }

    /**
     * @return Form
     */
    public function create(): Form
    {
        $form = parent::create(); // TODO: Change the autogenerated stub
        $defaultValues = [];
        foreach ($this->entityData as $k => $v) {
            if(isset($form[$k])) $defaultValues[$k] = $v;
        }
        $form->setDefaults($defaultValues);
        return self::createEditForm($form, (object)$this->entityData, "Aktualizovat změny");
    }

    /**
     * @throws InvalidLinkException
     * @throws AbortException
     */
    public function success(Form $form, array $data): void {
        $this->successTemplate($form, $data, new FormMessage("Entita " . $this->EAVRepository->entityName . " byla úspěšně aktualizována.", "Entita " . $this->EAVRepository->entityName . " nemohla být z neznámého důvodu aktualizována."), null, $this->rowUnique);
    }
}