<?php


namespace App\Forms\Product;


use App\Forms\FormOption;
use App\Forms\Product\Data\ProductFormData;
use App\Forms\RepositoryForm;
use App\Model\Database\Columns\URI;
use App\Model\Database\IRepository;
use App\Model\Database\Repository\Gallery\GalleryRepository;
use App\Model\Database\Repository\Product\ProductRepository;
use JetBrains\PhpStorm\Pure;
use Nette\Application\UI\Form;
use Nette\Application\UI\Presenter;
use Nette\Utils\DateTime;

/**
 * Class ProductForm
 * @package App\Forms\Product
 */
class ProductForm extends RepositoryForm
{
    /**
     * ProductForm constructor.
     * @param Presenter $presenter
     * @param ProductRepository $repository
     * @param GalleryRepository $galleryRepository
     */
    #[Pure] public function __construct(Presenter $presenter, ProductRepository $repository, protected GalleryRepository $galleryRepository)
    {
        parent::__construct($presenter, $repository);
        $this->presenter = $presenter;
    }

    /**
     * @return Form
     */
    public function create(): Form
    {
        $form = parent::create();
        $form->addText("title", "Název nabídky")->setRequired("Název nabídky musí být vyplněn.");
        $form->addText("miniature_url", "Miniatura nabídky")->setOption(FormOption::OPTION_NOTE, "Miniatura bude zobrazeno pouze na seznamu nabídek. Volte miniaturu jako URL adresu k nahranému obrázku.")->setRequired(false);
        $form->addTextArea("description", "Popis nabídky")
            ->setOption(FormOption::ACTIVE_WYSIWYG, 1)->setOption(FormOption::OPTION_NOTE, "Popis nabídky je zobrazen též na seznamu, nikoliv po rozkliknutí.")->setRequired(false);
        $form->addTextArea("content", "Obsah nabídky")
            ->setOption(FormOption::OPTION_NOTE, "Pokročilý popis nabídky, bude zobrazen po rozkliknutí")->setOption(FormOption::ACTIVE_WYSIWYG, 1);
        $galleries = $this->galleryRepository->findAll()->fetchAll();
        $select = [];
        foreach ($galleries as $gallery) {
            $select[$gallery->id] = $gallery->name;
        }
        $form->addSelect("gallery_id", "Vybrat galerii", $select)
            ->setPrompt("Vybrat galerii souvisejicí s nabídkou")
            ->setRequired(true);
        $form->addCheckbox("active", "Je možná poptávka na nabídku?")->setDefaultValue(1);
        $form->addCheckbox("show", "Zobrazit nabídku")->setDefaultValue(1);
        $form->addInteger("priority", "Priorita nabídku")->setOption(FormOption::OPTION_NOTE, "Čím větší číslo - tím větší priorita.")->setDefaultValue(0)->setRequired(false);
        $form->addSubmit("submit", "Vytvořit novou nabídku");
        return $form; // TODO: Change the autogenerated stub
    }

    /**
     * @param Form $form
     * @param ProductFormData $data
     */
    public function success(Form $form, ProductFormData &$data): void {
        $data->edited = new DateTime();
        $data->uri = new URI($data->title);
    }
}